db:
  type: mysql
  host: 'localhost'
  port: 3306
  username: root
  password: root
  database: 'msa-auth'
  synchronize: true

server:
  port: 8080

jwt:
  expiresIn: 3600
  secret: 'secret12321testgogo'