db-auth:
  type: mysql
  host: 'localhost'
  port: 3306
  username: root
  password: root
  database: msa-auth
  synchronize: true,
  logging: false,

db-price:
  type: mysql
  host: 'localhost'
  port: 3306
  username: root
  password: root
  database: msa-price
  synchronize: true,
  logging: false,

db-account:
  type: mysql
  host: 'localhost'
  port: 3306
  username: root
  password: root
  database: msa-account
  synchronize: true,
  logging: false,

db-portfolio:
  type: mysql
  host: 'localhost'
  port: 3306
  username: root
  password: root
  database: msa-portfolio
  synchronize: true,
  logging: false,

db-order:
  type: mysql
  host: 'localhost'
  port: 3306
  username: root
  password: root
  database: msa-order
  synchronize: true,
  logging: false,

db-order-log:
  type: mysql
  host: 'localhost'
  port: 3306
  username: root
  password: root
  database: msa-orderlog
  synchronize: true,
  logging: false,

server:
  port: 8080

jwt:
  expiresIn: 3600
  secret: 'secret12321testgogo'